#!/usr/bin/env python3
"""
Font bitmap deduplication post-processor for Adafruit_GFX font headers.

Reads a font .h file generated by fontconvert, finds duplicate (or embedded)
bitmap data across glyphs, and outputs a new .h file with deduplicated bitmaps
and adjusted glyph offsets.

Usage:
    python3 fontdedup.py FreeMono9pt7b.h > FreeMono9pt7b_dedup.h
    python3 fontdedup.py input.h -o output.h

The output format is identical to the input — the GFXfont/GFXglyph structures
are unchanged. Only the Bitmaps[] array is smaller and offsets are adjusted.
The renderer needs no modifications.
"""

import re
import sys
import argparse


def parse_font_header(filepath):
    """Parse an Adafruit_GFX font .h file and return its components.

    Returns a dict with:
        - header_lines: list of lines before the bitmaps array (includes, pragmas, etc.)
        - font_name: the base name used for C identifiers (e.g. 'FreeMono9pt7b')
        - bitmaps: bytes object with the raw bitmap data
        - glyphs: list of dicts with keys: bitmapOffset, width, height, xAdvance, xOffset, yOffset, comment
        - font_struct_line: the GFXfont struct definition line
        - approx_line: the '// Approx. N bytes' comment line (if present)
        - trailing_lines: any lines after the approx comment
    """
    with open(filepath, 'r') as f:
        content = f.read()

    # Extract font name from the bitmaps array declaration
    bm_match = re.search(r'const\s+uint8_t\s+(\w+)Bitmaps\s*\[\]\s*PROGMEM\s*=\s*\{', content)
    if not bm_match:
        raise ValueError("Could not find Bitmaps[] array declaration")
    font_name = bm_match.group(1)

    # Extract bitmap bytes
    bm_start = content.index('{', bm_match.start()) + 1
    # Find the matching closing brace
    depth = 1
    pos = bm_start
    while depth > 0:
        if content[pos] == '{':
            depth += 1
        elif content[pos] == '}':
            depth -= 1
        pos += 1
    bm_end = pos - 1
    bm_body = content[bm_start:bm_end]
    # Extract hex byte values using regex (handles inline comments, whitespace, etc.)
    bitmaps = bytes(int(h, 16) for h in re.findall(r'0x[0-9A-Fa-f]+', bm_body))

    # Extract glyph table entries
    glyph_match = re.search(r'const\s+GFXglyph\s+\w+Glyphs\s*\[\]\s*PROGMEM\s*=\s*\{', content)
    if not glyph_match:
        raise ValueError("Could not find Glyphs[] array declaration")

    glyph_start = content.index('{', glyph_match.start()) + 1
    depth = 1
    pos = glyph_start
    while depth > 0:
        if content[pos] == '{':
            depth += 1
        elif content[pos] == '}':
            depth -= 1
        pos += 1
    glyph_end = pos - 1
    glyph_body = content[glyph_start:glyph_end]

    # Parse individual glyph entries: { offset, width, height, xAdvance, xOffset, yOffset }
    glyph_pattern = re.compile(
        r'\{\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*\}'
        r'(?:\s*,?\s*//\s*(.*?))?$',
        re.MULTILINE
    )
    glyphs = []
    for m in glyph_pattern.finditer(glyph_body):
        glyphs.append({
            'bitmapOffset': int(m.group(1)),
            'width': int(m.group(2)),
            'height': int(m.group(3)),
            'xAdvance': int(m.group(4)),
            'xOffset': int(m.group(5)),
            'yOffset': int(m.group(6)),
            'comment': m.group(7).strip() if m.group(7) else '',
        })

    # Extract the GFXfont struct line
    font_match = re.search(
        r'const\s+GFXfont\s+\w+\s+PROGMEM\s*=\s*\{.*?\};',
        content, re.DOTALL
    )
    if not font_match:
        raise ValueError("Could not find GFXfont struct declaration")
    font_struct_line = font_match.group(0)

    # Extract approx bytes line
    approx_match = re.search(r'//\s*Approx\.\s*\d+\s*bytes', content)

    # Split header lines (everything before the bitmaps array)
    header_lines = content[:bm_match.start()].rstrip('\n').split('\n')

    # Trailing lines (after approx or after font struct)
    trailing_lines = []
    if approx_match:
        after_approx = content[approx_match.end():]
        trailing_lines = after_approx.rstrip('\n').split('\n') if after_approx.strip() else []

    return {
        'header_lines': header_lines,
        'font_name': font_name,
        'bitmaps': bitmaps,
        'glyphs': glyphs,
        'font_struct_line': font_struct_line,
        'approx_match': approx_match,
        'trailing_lines': trailing_lines,
    }


def glyph_byte_count(width, height):
    """Number of packed bytes for a glyph bitmap of given dimensions."""
    return (width * height + 7) // 8


def find_bytes(haystack, needle):
    """Find needle in haystack, return offset or -1."""
    # Simple search — data is small, no need for KMP
    n = len(needle)
    if n == 0:
        return 0
    for i in range(len(haystack) - n + 1):
        if haystack[i:i+n] == needle:
            return i
    return -1


def deduplicate(font_data):
    """Deduplicate bitmap data across glyphs.

    For each glyph, extract its bitmap bytes and check if those bytes already
    exist in the accumulated output buffer (as a substring). If so, reuse the
    existing offset. Otherwise, append the bytes and record the new offset.

    Returns (new_bitmaps, new_glyphs) where new_glyphs has updated bitmapOffsets.
    """
    bitmaps = font_data['bitmaps']
    glyphs = font_data['glyphs']

    out_buf = bytearray()
    new_glyphs = []

    for glyph in glyphs:
        w, h = glyph['width'], glyph['height']
        n_bytes = glyph_byte_count(w, h)
        offset = glyph['bitmapOffset']

        # Extract this glyph's bitmap bytes
        glyph_bytes = bitmaps[offset:offset + n_bytes]

        # Zero-size glyphs (e.g. space) all share offset 0
        if n_bytes == 0:
            new_glyph = dict(glyph)
            new_glyph['bitmapOffset'] = 0
            new_glyphs.append(new_glyph)
            continue

        # Search for this byte sequence in the accumulated output buffer
        found = find_bytes(out_buf, glyph_bytes)
        if found >= 0:
            # Reuse existing data
            new_glyph = dict(glyph)
            new_glyph['bitmapOffset'] = found
            new_glyphs.append(new_glyph)
        else:
            # Append new data
            new_offset = len(out_buf)
            out_buf.extend(glyph_bytes)
            new_glyph = dict(glyph)
            new_glyph['bitmapOffset'] = new_offset
            new_glyphs.append(new_glyph)

    return bytes(out_buf), new_glyphs


def format_bitmaps_array(font_name, bitmaps):
    """Format the bitmaps array as C source, matching the original style."""
    parts = [f'0x{b:02X}' for b in bitmaps]
    lines = [f'const uint8_t {font_name}Bitmaps[] PROGMEM = {{']
    for i in range(0, len(parts), 12):
        chunk = ', '.join(parts[i:i+12])
        lines.append(f'    {chunk},')
    # Remove trailing comma from last data line, add closing brace
    if lines[-1].endswith(','):
        lines[-1] = lines[-1][:-1] + ' };'
    return '\n'.join(lines)


def format_glyphs_array(font_name, glyphs):
    """Format the glyphs array as C source, matching the original style."""
    lines = [f'const GFXglyph {font_name}Glyphs[] PROGMEM = {{']
    for i, g in enumerate(glyphs):
        is_last = (i == len(glyphs) - 1)
        comma = '' if is_last else ','
        values = (f'{g["bitmapOffset"]:5d}, {g["width"]:3d}, {g["height"]:3d}, '
                  f'{g["xAdvance"]:3d}, {g["xOffset"]:4d}, {g["yOffset"]:4d}')
        entry = '    { ' + values + ' }' + comma
        if g['comment']:
            entry += '   // ' + g['comment']
        lines.append(entry)
    # Last entry gets closing brace
    lines.append('};')
    return '\n'.join(lines)


def write_output(font_data, new_bitmaps, new_glyphs, out):
    """Write the deduplicated font header to the output stream."""
    font_name = font_data['font_name']

    # Header lines (includes, pragmas)
    for line in font_data['header_lines']:
        print(line, file=out)

    # Bitmaps array
    print(file=out)  # blank line
    print(format_bitmaps_array(font_name, new_bitmaps), file=out)

    # Glyphs array
    print(file=out)
    print(format_glyphs_array(font_name, new_glyphs), file=out)

    # Font struct — update the name references in case they differ
    # (they shouldn't, but let's reconstruct it properly)
    font_struct = font_data['font_struct_line']
    print(file=out)
    print(font_struct, file=out)

    # Approx bytes comment
    num_glyphs = len(new_glyphs)
    first_char = new_glyphs[0]['comment'].split()[0] if new_glyphs else '0x20'
    # Parse first and last from the font struct
    struct_match = re.search(r'0x([0-9A-Fa-f]+)\s*,\s*0x([0-9A-Fa-f]+)', font_struct)
    if struct_match:
        first_val = int(struct_match.group(1), 16)
        last_val = int(struct_match.group(2), 16)
    else:
        first_val = 0x20
        last_val = 0x7E

    approx_bytes = len(new_bitmaps) + (last_val - first_val + 1) * 7 + 7
    print(f'// Approx. {approx_bytes} bytes', file=out)

    # Trailing lines
    for line in font_data['trailing_lines']:
        if line.strip():
            print(line, file=out)


def main():
    parser = argparse.ArgumentParser(
        description='Deduplicate bitmap data in Adafruit_GFX font headers'
    )
    parser.add_argument('input', help='Input font .h file')
    parser.add_argument('-o', '--output', help='Output file (default: stdout)')
    args = parser.parse_args()

    font_data = parse_font_header(args.input)

    original_size = len(font_data['bitmaps'])
    new_bitmaps, new_glyphs = deduplicate(font_data)
    new_size = len(new_bitmaps)

    # Report savings to stderr
    saved = original_size - new_size
    pct = (saved / original_size * 100) if original_size > 0 else 0
    print(f'Bitmap data: {original_size} -> {new_size} bytes '
          f'({saved} bytes saved, {pct:.1f}%)', file=sys.stderr)

    # Count how many glyphs were deduplicated
    dedup_count = sum(1 for g in new_glyphs
                      if g['bitmapOffset'] != font_data['glyphs'][new_glyphs.index(g)]['bitmapOffset']
                      and glyph_byte_count(g['width'], g['height']) > 0)
    # More accurate count
    dedup_count = 0
    for orig, new in zip(font_data['glyphs'], new_glyphs):
        if (orig['bitmapOffset'] != new['bitmapOffset'] and
                glyph_byte_count(orig['width'], orig['height']) > 0):
            dedup_count += 1
    print(f'Glyphs deduplicated: {dedup_count}/{len(new_glyphs)}', file=sys.stderr)

    out = open(args.output, 'w') if args.output else sys.stdout
    try:
        write_output(font_data, new_bitmaps, new_glyphs, out)
    finally:
        if args.output:
            out.close()


if __name__ == '__main__':
    main()
